### ISSUE TITLE
"Error! Could not generate a preview"

### ISSUE THREAD

**Issue by Georg380** [owncloud/gallery#169]
### Steps to reproduce
1. Open a folder with pictures
2. Open a picture
### Expected behaviour

Step 1: Thumbnails of all the pictures in the folder should be visibile.
Step 2: A preview of the opened photo should appear.
### Actual behaviour

Step 1: No thumbnails visibile of photos, that are bigger than 3.5MB. With smaller pictures there is no problem. ---> New finding: The problem exists independend of the size of the pictures!
Step 2: No preview appears (of pictures over 3.5MB) but instead on the top of the page: "Error! Could not generate a preview"
![owncloud error](https://cloud.githubusercontent.com/assets/12801368/8041624/e0a2d2fa-0e19-11e5-80f7-bf598e4ce0d8.jpg)
### Server configuration

**Operating system**: Linux

**Web server:** Apache/2.2.22

**Database:** MySQL

**PHP version:** 5.6

**ownCloud version:** 8.0.3

**Updated from an older ownCloud or fresh install:** updated

**List of activated apps:** Activity, Deleted files, First Run Wizard, Gallery, Mail Template Editor, PDF Viewer, Share Files, Text Editor, Updater, Versions, Video Viewer

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc3b27d7a11a',
  'passwordsalt' => '123',
  'secret' => '123',
  'trusted_domains' => 
  array (
    0 => 'xyz.online.de',
 ),
  'datadirectory' => '/homepages/41/d549415189/htdocs/hercynia/data',
  'overwrite.cli.url' => 'http://xyz.online.de/hercynia',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'db123456789',
  'dbhost' => 'db123456789.db.1and1.com',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'dbo123456789',
  'dbpassword' => 'xyz',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no
### Client configuration

**Browser:** Firefox and Chrome

**Operating system:** Windows 7
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
{"reqId":"902d965cb98f90ff0c37d91c05aeb992","remoteAddr":"1.2.3.4","app":"index","message":"Exception: {\"Message\":\"Unable to generate a URL for the named route \\\"galleryplus.page.index\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/lib\\\/private\\\/route\\\/router.php(282): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('galleryplus.pag...', Array, false)\\n#1 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/lib\\\/private\\\/urlgenerator.php(42): OC\\\\Route\\\\Router->generate('galleryplus.pag...', Array)\\n#2 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/apps\\\/galleryplus\\\/appinfo\\\/app.php(36): OC\\\\URLGenerator->linkToRoute('galleryplus.pag...')\\n#3 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/lib\\\/private\\\/app.php(386): require('\\\/homepages\\\/41\\\/d...')\\n#4 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/settings\\\/ajax\\\/navigationdetect.php(9): OC_App::getAppNavigationEntries('galleryplus')\\n#5 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/homepages\\\/41\\\/d...')\\n#6 [internal function]: __lambda_func(Array)\\n#7 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('\\\\x00lambda_63', Array)\\n#8 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/lib\\\/base.php(782): OC\\\\Route\\\\Router->match('\\\/settings\\\/ajax\\\/...')\\n#9 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/index.php(36): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/3rdparty\\\/symfony\\\/routing\\\/Symfony\\\/Component\\\/Routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":134}","level":4,"time":"2015-06-08T16:48:23+00:00"}
{"reqId":"89bfc5c29c0593e0d0daf75af874ed93","remoteAddr":"1.2.3.4","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1230","level":3,"time":"2015-06-08T16:48:25+00:00"}
{"reqId":"89bfc5c29c0593e0d0daf75af874ed93","remoteAddr":"1.2.3.4","app":"PHP","message":"Invalid argument supplied for foreach() at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1233","level":3,"time":"2015-06-08T16:48:25+00:00"}
{"reqId":"25fc61e5f0b360020cd4f6794867fadc","remoteAddr":"1.2.3.4","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1230","level":3,"time":"2015-06-08T16:48:36+00:00"}
{"reqId":"25fc61e5f0b360020cd4f6794867fadc","remoteAddr":"1.2.3.4","app":"PHP","message":"Invalid argument supplied for foreach() at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1233","level":3,"time":"2015-06-08T16:48:36+00:00"}
{"reqId":"9875167f56da7b46e9685fbfadb694c9","remoteAddr":"1.2.3.4","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1230","level":3,"time":"2015-06-08T16:53:55+00:00"}
{"reqId":"9875167f56da7b46e9685fbfadb694c9","remoteAddr":"1.2.3.4","app":"PHP","message":"Invalid argument supplied for foreach() at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1233","level":3,"time":"2015-06-08T16:53:55+00:00"}
{"reqId":"38cb1f1007bd397419c488ccf2fa6c6b","remoteAddr":"1.2.3.4","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1230","level":3,"time":"2015-06-08T16:55:40+00:00"}
{"reqId":"38cb1f1007bd397419c488ccf2fa6c6b","remoteAddr":"1.2.3.4","app":"PHP","message":"Invalid argument supplied for foreach() at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1233","level":3,"time":"2015-06-08T16:55:40+00:00"}
{"reqId":"ed8bbc2d5846b9f13faae6b585f4bf78","remoteAddr":"1.2.3.4","app":"webdav","message":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC_Connector_Sabre_MaintenancePlugin->checkMaintenanceMode('PROPFIND', '')\\n#1 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#2 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#3 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PROPFIND', '')\\n#4 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/remote.php(54): require_once('\\\/homepages\\\/41\\\/d...')\\n#6 {main}\",\"File\":\"\\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/lib\\\/private\\\/connector\\\/sabre\\\/maintenanceplugin.php\",\"Line\":49}","level":4,"time":"2015-06-08T16:56:12+00:00"}
{"reqId":"c0204d69d02438a9b3186768b598eb6b","remoteAddr":"1.2.3.4","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1230","level":3,"time":"2015-06-08T17:06:14+00:00"}
{"reqId":"c0204d69d02438a9b3186768b598eb6b","remoteAddr":"1.2.3.4","app":"PHP","message":"Invalid argument supplied for foreach() at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1233","level":3,"time":"2015-06-08T17:06:14+00:00"}
{"reqId":"ec0c5b6d57a2c9972d7834dd925c6162","remoteAddr":"1.2.3.4","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1230","level":3,"time":"2015-06-08T17:06:36+00:00"}
{"reqId":"ec0c5b6d57a2c9972d7834dd925c6162","remoteAddr":"1.2.3.4","app":"PHP","message":"Invalid argument supplied for foreach() at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1233","level":3,"time":"2015-06-08T17:06:36+00:00"}
{"reqId":"f2642af3d6912c1c325a8b3d4fef8efe","remoteAddr":"1.2.3.4","app":"index","message":"Exception: {\"Message\":\"Unable to generate a URL for the named route \\\"galleryplus.page.index\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/lib\\\/private\\\/route\\\/router.php(282): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('galleryplus.pag...', Array, false)\\n#1 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/lib\\\/private\\\/urlgenerator.php(42): OC\\\\Route\\\\Router->generate('galleryplus.pag...', Array)\\n#2 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/apps\\\/galleryplus\\\/appinfo\\\/app.php(37): OC\\\\URLGenerator->linkToRoute('galleryplus.pag...')\\n#3 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/lib\\\/private\\\/app.php(386): require('\\\/homepages\\\/41\\\/d...')\\n#4 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/settings\\\/ajax\\\/navigationdetect.php(9): OC_App::getAppNavigationEntries('galleryplus')\\n#5 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/homepages\\\/41\\\/d...')\\n#6 [internal function]: __lambda_func(Array)\\n#7 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('\\\\x00lambda_63', Array)\\n#8 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/lib\\\/base.php(782): OC\\\\Route\\\\Router->match('\\\/settings\\\/ajax\\\/...')\\n#9 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/index.php(36): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/3rdparty\\\/symfony\\\/routing\\\/Symfony\\\/Component\\\/Routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":134}","level":4,"time":"2015-06-08T17:06:44+00:00"}
{"reqId":"5bfd514f09f080063b222cd5ef24aa11","remoteAddr":"1.2.3.4","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1230","level":3,"time":"2015-06-08T17:06:46+00:00"}
{"reqId":"5bfd514f09f080063b222cd5ef24aa11","remoteAddr":"1.2.3.4","app":"PHP","message":"Invalid argument supplied for foreach() at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1233","level":3,"time":"2015-06-08T17:06:46+00:00"}
{"reqId":"70ccda6f2413d67680b44a0d74b391e5","remoteAddr":"1.2.3.4","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1230","level":3,"time":"2015-06-08T17:07:20+00:00"}
{"reqId":"70ccda6f2413d67680b44a0d74b391e5","remoteAddr":"1.2.3.4","app":"PHP","message":"Invalid argument supplied for foreach() at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1233","level":3,"time":"2015-06-08T17:07:20+00:00"}
{"reqId":"01542da73e666116bbf501ad13aa3eb1","remoteAddr":"1.2.3.4","app":"PHP","message":"fopen(\/homepages\/41\/d549415189\/htdocs\/hercynia\/data\/Georg\/files\/Website\/IMG_6147.JPG): failed to open stream: No such file or directory at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/files\/storage\/local.php#216","level":3,"time":"2015-06-08T17:08:12+00:00"}
{"reqId":"99a0ccc61c65e0c2de34d4144d13fa74","remoteAddr":"1.2.3.4","app":"PHP","message":"fopen(\/homepages\/41\/d549415189\/htdocs\/hercynia\/data\/Georg\/files\/Website\/IMG_6147.JPG): failed to open stream: No such file or directory at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/files\/storage\/local.php#216","level":3,"time":"2015-06-08T17:08:36+00:00"}
{"reqId":"9cae87baae4f5cc32a87a4a28206507b","remoteAddr":"1.2.3.4","app":"PHP","message":"fopen(\/homepages\/41\/d549415189\/htdocs\/hercynia\/data\/Georg\/files\/Website\/IMG_7727.JPG): failed to open stream: No such file or directory at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/files\/storage\/local.php#216","level":3,"time":"2015-06-08T17:08:42+00:00"}
{"reqId":"b169c8578533f25e53e595bb276e503e","remoteAddr":"1.2.3.4","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1230","level":3,"time":"2015-06-08T17:09:12+00:00"}
{"reqId":"b169c8578533f25e53e595bb276e503e","remoteAddr":"1.2.3.4","app":"PHP","message":"Invalid argument supplied for foreach() at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1233","level":3,"time":"2015-06-08T17:09:12+00:00"}
{"reqId":"6d1c4736086eefc2a7b629157a08ff07","remoteAddr":"1.2.3.4","app":"index","message":"Exception: {\"Message\":\"Unable to generate a URL for the named route \\\"gallery_index\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/lib\\\/private\\\/route\\\/router.php(282): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('gallery_index', Array, false)\\n#1 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/lib\\\/private\\\/urlgenerator.php(42): OC\\\\Route\\\\Router->generate('gallery_index', Array)\\n#2 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/lib\\\/private\\\/helper.php(112): OC\\\\URLGenerator->linkToRoute('gallery_index', Array)\\n#3 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/lib\\\/public\\\/util.php(219): OC_Helper::linkToRoute('gallery_index', Array)\\n#4 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/apps\\\/gallery\\\/appinfo\\\/app.php(31): OCP\\\\Util::linkToRoute('gallery_index')\\n#5 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/lib\\\/private\\\/app.php(386): require('\\\/homepages\\\/41\\\/d...')\\n#6 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/settings\\\/ajax\\\/navigationdetect.php(9): OC_App::getAppNavigationEntries('gallery')\\n#7 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/homepages\\\/41\\\/d...')\\n#8 [internal function]: __lambda_func(Array)\\n#9 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('\\\\x00lambda_63', Array)\\n#10 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/lib\\\/base.php(782): OC\\\\Route\\\\Router->match('\\\/settings\\\/ajax\\\/...')\\n#11 \\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/index.php(36): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/homepages\\\/41\\\/d549415189\\\/htdocs\\\/hercynia\\\/3rdparty\\\/symfony\\\/routing\\\/Symfony\\\/Component\\\/Routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":134}","level":4,"time":"2015-06-08T17:09:18+00:00"}
{"reqId":"7261e368d5cf72f4562658f95ef72e3c","remoteAddr":"1.2.3.4","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1230","level":3,"time":"2015-06-08T17:09:19+00:00"}
{"reqId":"7261e368d5cf72f4562658f95ef72e3c","remoteAddr":"1.2.3.4","app":"PHP","message":"Invalid argument supplied for foreach() at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1233","level":3,"time":"2015-06-08T17:09:19+00:00"}
{"reqId":"f5273d9e75a58b0e854799cada13b697","remoteAddr":"1.2.3.4","app":"PHP","message":"Array to string conversion at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/l10n\/string.php#75","level":3,"time":"2015-06-08T17:09:45+00:00"}
{"reqId":"7cb0546fcd43c5fc86cb2616667d56af","remoteAddr":"1.2.3.4","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2015-06-08T17:23:13+00:00"}

```

**Comment by weipah** [comment]
Hi @Georg380 
I don't think this is an issue, but rather a misconfiguration somewhere.

I can preview photos bigger than 5mb for example.

Have you checked your php-config / mysql-config / apache2-config; sounds like somewhere you have a limit set for 3.5Meg?

On a sidenote I think OC 8.0.4 was released as latest stable.

Which version of gallery+ do you have in place?

**Comment by oparoz** [comment]
From the logs, I can see two problems:
- Pictures/gallery app seems to be still enabled. If it's not the case, make sure the folder in /apps is named galleryplus and make sure you've refreshed the browser with ctrl+F5
- 2 JPGs are not available. I don't know yet if it's a Pictures or a caching issue.

So, @Georg380, the first problem should be easy to fix and there is nothing we can do about the second one, the pictures are not there anymore.

**Comment by Georg380** [comment]
@weipah 
I've just tried again to load pictures and found out that it doesn't depend on the size of the picture. I got a preview of a 4MB-picture, but the with the next picture with 3.5MB the problem occured again. 
If I use the Owncloud-Updater it tells me that I'm using the latest version...
My version of Gallery+ is 8.0.11

@oparoz 
The pictures-app is definitely disabled. Now i even deleted the gallery-folder. Only Gallery+ is running.

**Comment by oparoz** [comment]
Ok, so now if your folder is named galleryplus, then only the files which can't be found will throw that error in the browser.

You should try to download and view those files on your desktop to see if Gallery is mistaken. If you can't access them, then you will need to re-upload the originals. If you can, then we need to figure out why Gallery can't.

**Comment by Georg380** [comment]
There's no problem with the pictures, when I download them on my desktop. So it's clear, that the pictures exist on the server and should be found by the gallery-app...

**Comment by oparoz** [comment]
Do you have thumbnails of these pictures in the Gallery?
Would it be possible to launch the slideshow and go through all the pictures of the folder and then check the logs to see if it reports as many broken files as you see in the browser? Your logs only show 2 broken pictures.

**Comment by Georg380** [comment]
No, there aren't thumbnails of these pictures either.
Here is the owncloud.log after I tried to open some more not-working-pictures:

```
{"reqId":"ff3b3665ca69bd0e6ccfc7d4f83e6265","remoteAddr":"94.216.161.58","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1230","level":3,"time":"2015-06-08T18:12:03+00:00"}
{"reqId":"ff3b3665ca69bd0e6ccfc7d4f83e6265","remoteAddr":"94.216.161.58","app":"PHP","message":"Invalid argument supplied for foreach() at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1233","level":3,"time":"2015-06-08T18:12:03+00:00"}
{"reqId":"61e08ad7e980c12511ff2307d12faf59","remoteAddr":"94.216.161.58","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2015-06-08T18:24:02+00:00"}
{"reqId":"87293d5ee8aa56dad82b4c67028e48fc","remoteAddr":"94.216.161.58","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2015-06-08T18:34:14+00:00"}
{"reqId":"66121b75d16655933d5dbdb72017d72d","remoteAddr":"94.216.161.58","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2015-06-08T18:50:20+00:00"}
{"reqId":"f9f8624d43fbdf97c6d03318e89c0f84","remoteAddr":"94.216.161.58","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2015-06-08T21:41:17+00:00"}
{"reqId":"ca19da6ffade0b32efb9acc4f481804f","remoteAddr":"88.66.213.3","app":"PHP","message":"Array to string conversion at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/l10n\/string.php#75","level":3,"time":"2015-06-09T10:09:31+00:00"}
{"reqId":"cdda892d644eb0cf656bf54315e0cd33","remoteAddr":"88.66.213.3","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1230","level":3,"time":"2015-06-09T10:10:43+00:00"}
{"reqId":"cdda892d644eb0cf656bf54315e0cd33","remoteAddr":"88.66.213.3","app":"PHP","message":"Invalid argument supplied for foreach() at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1233","level":3,"time":"2015-06-09T10:10:43+00:00"}
{"reqId":"e1219b0acb0ceff91f57da9e995baec2","remoteAddr":"88.66.213.3","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1230","level":3,"time":"2015-06-09T10:10:53+00:00"}
{"reqId":"e1219b0acb0ceff91f57da9e995baec2","remoteAddr":"88.66.213.3","app":"PHP","message":"Invalid argument supplied for foreach() at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1233","level":3,"time":"2015-06-09T10:10:53+00:00"}
{"reqId":"c583ad544bf293b8968c85d996da0bca","remoteAddr":"88.66.213.3","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1230","level":3,"time":"2015-06-09T10:12:55+00:00"}
{"reqId":"c583ad544bf293b8968c85d996da0bca","remoteAddr":"88.66.213.3","app":"PHP","message":"Invalid argument supplied for foreach() at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1233","level":3,"time":"2015-06-09T10:12:55+00:00"}
{"reqId":"d2fde375d2aef1384ca617e1680de3aa","remoteAddr":"88.66.213.3","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1230","level":3,"time":"2015-06-09T10:13:09+00:00"}
{"reqId":"d2fde375d2aef1384ca617e1680de3aa","remoteAddr":"88.66.213.3","app":"PHP","message":"Invalid argument supplied for foreach() at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1233","level":3,"time":"2015-06-09T10:13:09+00:00"}
{"reqId":"bc38212db59ccf7bd3caefbc0aa56f73","remoteAddr":"88.66.213.3","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1230","level":3,"time":"2015-06-09T10:13:44+00:00"}
{"reqId":"bc38212db59ccf7bd3caefbc0aa56f73","remoteAddr":"88.66.213.3","app":"PHP","message":"Invalid argument supplied for foreach() at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1233","level":3,"time":"2015-06-09T10:13:44+00:00"}
{"reqId":"e45b1ea3b63a9d9cdac32bdf3db994fc","remoteAddr":"88.66.213.3","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1230","level":3,"time":"2015-06-09T10:13:51+00:00"}
{"reqId":"e45b1ea3b63a9d9cdac32bdf3db994fc","remoteAddr":"88.66.213.3","app":"PHP","message":"Invalid argument supplied for foreach() at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1233","level":3,"time":"2015-06-09T10:13:51+00:00"}
{"reqId":"6a3b2766b15626bebd0175146dee4bb6","remoteAddr":"88.66.213.3","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1230","level":3,"time":"2015-06-09T10:22:10+00:00"}
{"reqId":"6a3b2766b15626bebd0175146dee4bb6","remoteAddr":"88.66.213.3","app":"PHP","message":"Invalid argument supplied for foreach() at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1233","level":3,"time":"2015-06-09T10:22:10+00:00"}
{"reqId":"9ef57a9c465b8a1fadc82c852ccbf8b7","remoteAddr":"88.66.213.3","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1230","level":3,"time":"2015-06-09T10:22:18+00:00"}
{"reqId":"9ef57a9c465b8a1fadc82c852ccbf8b7","remoteAddr":"88.66.213.3","app":"PHP","message":"Invalid argument supplied for foreach() at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1233","level":3,"time":"2015-06-09T10:22:18+00:00"}
{"reqId":"4d22d5e674860209c1cf2be1c7d8eb94","remoteAddr":"88.66.213.3","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1230","level":3,"time":"2015-06-09T10:22:43+00:00"}
{"reqId":"4d22d5e674860209c1cf2be1c7d8eb94","remoteAddr":"88.66.213.3","app":"PHP","message":"Invalid argument supplied for foreach() at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1233","level":3,"time":"2015-06-09T10:22:43+00:00"}
{"reqId":"9a9bb8e45ae51640e32ca172404d42cf","remoteAddr":"88.66.213.3","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1230","level":3,"time":"2015-06-09T10:23:21+00:00"}
{"reqId":"9a9bb8e45ae51640e32ca172404d42cf","remoteAddr":"88.66.213.3","app":"PHP","message":"Invalid argument supplied for foreach() at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1233","level":3,"time":"2015-06-09T10:23:21+00:00"}
{"reqId":"f60bb0672686936ca83a988d263e5796","remoteAddr":"88.66.213.3","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1230","level":3,"time":"2015-06-09T10:32:42+00:00"}
{"reqId":"f60bb0672686936ca83a988d263e5796","remoteAddr":"88.66.213.3","app":"PHP","message":"Invalid argument supplied for foreach() at \/homepages\/41\/d549415189\/htdocs\/hercynia\/lib\/private\/app.php#1233","level":3,"time":"2015-06-09T10:32:42+00:00"}

```

**Comment by oparoz** [comment]
OK, so there is nothing in the logs, so it must be a browser issue.

Could you press F12 and go to the network tab? You'll be asked to press reload.
Now when loading an image which doesn't work. What error number do you see?
Is there an error message in the console?

**Comment by Georg380** [comment]
That is how my console looks like:
![console](https://cloud.githubusercontent.com/assets/12801368/8057505/21163622-0eb2-11e5-805d-8f26530f23d8.jpg)
Nothing happens in the console, when I try to open a photo.

Can it be a browser issue if the error also occurs in Google Chrome?

**Comment by weipah** [comment]
@oparoz seems to be a known issue 
https://github.com/owncloud/core/issues/10314
https://github.com/owncloud/core/issues/16091

@Georg380 can you try to disable all extensions in Chrome? Or maybe start a Firefox in Safe-mode or similar?

**Comment by oparoz** [comment]
@Georg380 - It would be a javascript issue, but only the browser can help us figure it out. 
I can see that this is a screenshot of the Files app and you're not getting any previews there. That means this is an issue with core or your files which can't be read properly, not with the Gallery app. Please open a ticket [there](https://github.com/owncloud/core/issues). You can copy paste the content of your first post, but in your title, mention that you're not getting any thumbnails in the Files app.
I'll be able to help you there.

@weipah - Those issues only happen on Firefox and are not blocking the rendering afaik. I get the same.

**Comment by Georg380** [comment]
Thank you, I did as you recommended. You can find the new issue here: owncloud/core#16837

**Comment by NetBUG** [comment]
I encounter the same issue with my installation.
I have 10.0.3.3 upgraded from 9.something, the previews are generated for the files (including those over 3.5 Mb), but image viewer shows black screen with an error on the top.
Chrome console shows 500 or 400 error when fetching it.
Gallery app is not working as well.

**Comment by revoltown** [comment]
i have the same problem as from pirst post, can any one help ?
