### ISSUE TITLE
OC 8.1.3 Update from 13.0 to 14.1 fails

### ISSUE THREAD

**Issue by Siedlerchr** [owncloud/gallery#437]
Updating Gallery from 13.0 to 14.1 fails due do unauthorized code
### Steps to reproduce
1. Go to Deactived Apps
2. Click Update on Gallery
### Expected behaviour

The app should update without errors
### Actual behaviour

Error message: Update failed, the app contains unauthorized Code
OCL Log Error
### Server configuration

**Operating system**:
Apache-Version  2.4.10
PHP-Version 5.4.33
MySQL-Version   5.6.23
Architecture: x86_64
OS:  linux
Kernel-Version  2.6.32-042stab102.9

**ownCloud version:** (see ownCloud admin page)
8.1.3 (stable)

**Updated from an older ownCloud or fresh install:**
Previous versions

**List of activated apps:**

```
Enabled:
 - external: 1.2
 - files: 1.1.10
 - files_external: 0.2.3
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - updater: 0.6
 - user_external: 0.4
Disabled:
 - activity
 - encryption
 - gallery
 - galleryplus
 - provisioning_api
 - templateeditor
 - user_ldap
 - user_webdavauth
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '522b44e093443',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'datadirectory' => '/home/xxxxxxxxxxxxxx/public_html/data',
  'dbtype' => 'mysql',
  'version' => '8.1.3.0',
  'dbname' => 'xxxxxxxxxx_owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'siedlerc_ocl',
  'dbpassword' => 'xxxxxxxxxxxxxxxxxxx',
  'installed' => true,
  'forcessl' => true,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'loglevel' => 1,
  'logdateformat' => 'F d, Y H:i:s',
  'logtimezone' => 'Europe/Berlin',
  'appstoreenabled' => true,
  'appstoreurl' => 'https://api.owncloud.com/v1',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/home/xxxxxxxxxxxx/public_html/apps',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
  'appcodechecker' => true,
  'enable_previews' => true,
  'theme' => '',
  'maintenance' => false,
  'updatechecker' => true,
  'has_internet_connection' => true,
  'check_for_working_webdav' => true,
  'check_for_working_htaccess' => true,
  'trusted_domains' => 
  array (
    0 => 'xxxxxxxxxxxxxxxxxx.xxxxxxxxxxxx.com',
  ),
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxx',
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
OwnCloud

**Are you using encryption:** yes/no
NO, only SSL

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO
### Client configuration

**Browser:**
Firefox latest version
**Operating system:**
Win 7  X64
#### Web server error log

```
```
#### ownCloud log (data/owncloud.log)

```
Undefined variable: undefinedVariable at /home/xxxxxxxxxx/public_html/3rdparty/nikic/php-parser/lib/PhpParser/Lexer.php#68
Exception: {"Message":"HTTP\/1.1 503 System in maintenance mode.","Code":0,"Trace":"#0 [internal function]: OC\\Connector\\Sabre\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/home\/xxxxxxxxx\/public_html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/home\/xxxxxxxxxxxxxxxxxxx\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/home\/xxxxxxxxxxxxxxxxxxxx\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/home\/xxxxxxxxxxxxxxxxxxxxxx\/public_html\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#5 \/home\/xxxxxxxxxxxxxxxxxxxx\/public_html\/remote.php(132): require_once('\/home\/xxxxxxxxxxxxxxx\/...')\n#6 {main}","File":"\/home\/xxxxxxxxxxxxxxxxxxxxxxx\/public_html\/lib\/private\/connector\/sabre\/maintenanceplugin.php","Line":83}
```
#### Browser log

```
No errors
```

**Comment by oparoz** [comment]
Hello,

You have this setting enabled: `'appcodechecker' => true,` and it's currently impossible to write compliant code using the tools provided by `core` when accessing the filesystem. This might be solved some day as the people in charge are aware of the problem, but this hasn't happened yet.

If you want to see where the non-compliant code is used, you can use the occ tool.

`$ sudo -uwww-data ./occ app:check-code gallery`

**Comment by Siedlerchr** [comment]
Ah Thanks, I set the config flag to false and now the update worked

**Comment by oparoz** [comment]
Updated the documentation so that people know what to do next time
