### ISSUE TITLE
Gallery app version 16.0.2 does not show the images with oC 10.0.9. RC3 version

### ISSUE THREAD

**Issue by davitol** [owncloud/gallery#777]
### Steps to reproduce

1.  Upload images to your oC Server
2. Go to Gallery section

### Expected behaviour
The images should be shown  in the gallery

### Actual behaviour
The images are NOT shown  in the gallery and a log is spotted in owncloud.log file.

![screen shot 2018-07-09 at 12 34 35](https://user-images.githubusercontent.com/10596560/42447276-93f6238e-8379-11e8-9781-5f849a95c4fc.png)

```
{"reqId":"vNZpqvdwrEH07LREOPE7","level":3,"time":"2018-07-09T10:44:19+00:00","remoteAddr":"172.18.0.1","user":"admin","app":"index","method":"GET","url":"\/apps\/gallery\/thumbnails?ids=18&scale=1&square=0&requesttoken=E1UcdgkEOC1gAg8vJxAHbXwVDA87FhkOA1IxUwM4SgU%3D%3AgaqBjRhe9nKwIe1BNbbbsfH8mcRa3B9Vp8tXRzUlHD4%3D","message":"Exception: {\"Exception\":\"TypeError\",\"Message\":\"Argument 3 passed to OC\\\\Preview::__construct() must implement interface OCP\\\\Files\\\\Node, string given, called in \\\/mnt\\\/data\\\/apps\\\/gallery\\\/preview\\\/preview.php on line 100\",\"Code\":0,\"Trace\":\"#0 \\\/mnt\\\/data\\\/apps\\\/gallery\\\/preview\\\/preview.php(100): OC\\\\Preview->__construct('admin', 'files', 'asda\\\/Screen Sho...')\\n#1 \\\/mnt\\\/data\\\/apps\\\/gallery\\\/service\\\/previewservice.php(107): OCA\\\\Gallery\\\\Preview\\\\Preview->setupView('admin', Object(OC\\\\Files\\\\Node\\\\File), 'asda\\\/Screen Sho...')\\n#2 \\\/mnt\\\/data\\\/apps\\\/gallery\\\/controller\\\/preview.php(167): OCA\\\\Gallery\\\\Service\\\\PreviewService->createPreview(Object(OC\\\\Files\\\\Node\\\\File), 400, 200, true, true)\\n#3 \\\/mnt\\\/data\\\/apps\\\/gallery\\\/controller\\\/preview.php(117): OCA\\\\Gallery\\\\Controller\\\\PreviewController->getPreviewData(Object(OC\\\\Files\\\\Node\\\\File), false, 400, 200, true, true)\\n#4 \\\/mnt\\\/data\\\/apps\\\/gallery\\\/controller\\\/preview.php(86): OCA\\\\Gallery\\\\Controller\\\\PreviewController->getData(18, 400, 200, true, false, true)\\n#5 \\\/mnt\\\/data\\\/apps\\\/gallery\\\/controller\\\/previewcontroller.php(103): OCA\\\\Gallery\\\\Controller\\\\PreviewController->getThumbnail(18, false, '1')\\n#6 [internal function]: OCA\\\\Gallery\\\\Controller\\\\PreviewController->getThumbnails('18', false, '1')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Gallery\\\\Controller\\\\PreviewController), 'getThumbnails')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(103): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Gallery\\\\Controller\\\\PreviewController), 'getThumbnails')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('PreviewControll...', 'getThumbnails', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(919): OC\\\\Route\\\\Router->match('\\\/apps\\\/gallery\\\/t...')\\n#14 \\\/var\\\/www\\\/owncloud\\\/index.php(55): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Preview.php\",\"Line\":112}"}
```

### Server configuration

**Operating system**:
Ubuntu 16.04
**Web server:**
PHP dev server
**Database:**
mySQL
**PHP version:**
7.1
ownCloud
**cloud version:** 
core stable10 at  10.0.9RC3 and Gallery app in MarketPlace ```v.16.0.2```

**Comment by DeepDiver1975** [comment]
Not relevant - this is why we will release 16.1.0 - https://github.com/owncloud/gallery/pull/770
