### ISSUE TITLE
Gallery 16.1.0 broken with gallery.cnf (Class 'Symfony\Component\Yaml\Parser' not found)

### ISSUE THREAD

**Issue by ho4ho** [owncloud/gallery#809]
### Steps to reproduce

1. Use https://github.com/owncloud/gallery/wiki/Gallery-configuration
2. Open gallery
3. Watch broken gallery

### Expected behaviour
Gallery work with gallery.cnf

### Actual behaviour
Gallery broken with gallery.cnf
Caused of https://github.com/owncloud/gallery/commit/3a8a560c605a2049dd8c53c9a83ce4eeabc469ce because exclude https://github.com/owncloud/gallery/tree/stable10/vendor/symfony/yaml?

### Server configuration

**cloud server:** ownCloud

**cloud version:** 10.0.10

**Updated from an older installation or fresh install:** Updated

**List of activated apps:**

<details>
<summary>App list</summary>

```
  - gallery: 16.1.0
```

</details>
 
**Are you using custom gallery.cnf config files:** yes

#### Cloud log

<details>
<summary>Cloud log</summary>

```
{"reqId":"","level":3,"time":"","remoteAddr":"","user":"","app":"index","method":"GET","url":"\/apps\/gallery\/config","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'Symfony\\\\Component\\\\Yaml\\\\Parser' not found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/gallery\\\/config\\\/configparser.php(47): OCA\\\\Gallery\\\\Config\\\\ConfigParser->parseConfig(Object(OC\\\\Files\\\\Node\\\\Folder), 'gallery.cnf')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/gallery\\\/service\\\/configservice.php(104): OCA\\\\Gallery\\\\Config\\\\ConfigParser->getFeaturesList(Object(OC\\\\Files\\\\Node\\\\Folder), 'gallery.cnf')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/gallery\\\/controller\\\/config.php(47): OCA\\\\Gallery\\\\Service\\\\ConfigService->getFeaturesList()\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/gallery\\\/controller\\\/configcontroller.php(63): OCA\\\\Gallery\\\\Controller\\\\ConfigController->getConfig(false)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(153): OCA\\\\Gallery\\\\Controller\\\\ConfigController->get(false)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(85): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Gallery\\\\Controller\\\\ConfigController), 'get')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Gallery\\\\Controller\\\\ConfigController), 'get')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('ConfigControlle...', 'get', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(909): OC\\\\Route\\\\Router->match('\\\/apps\\\/gallery\\\/c...')\\n#10 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/gallery\\\/config\\\/configparser.php\",\"Line\":94}"}
```
</details>

**Comment by ho4ho** [comment]
#809 trying fix

**Comment by ho4ho** [comment]
#840 new fixing
